services:
  app:
    build: ".docker/local/php"
    working_dir: /app
    volumes:
      - ".:/app"
      - "./.docker/local/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./.docker/local/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf"
    ports:
      - "${APP_PHP_PORT:-9000}:9000"
      - "${APP_VITE_PORT:-5173}:5173"
      - "${APP_STORYBOOK_PORT:-6006}:6006"
    environment:
      - USER_NAME
      - USER_ID
      - GROUP_NAME
      - GROUP_ID
      - OS_NAME
    depends_on:
      - mysql
      - redis
      - minio
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    build: ".docker/local/nginx"
    platform: linux/arm64/v8
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./public:/app/public
      - ./.docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  queue_worker:
    build: ".docker/local/php"
    working_dir: "/app"
    command: "php artisan queue:work --tries=3 --queue=high,default,low"
    environment:
      - USER_NAME
      - USER_ID
      - GROUP_NAME
      - GROUP_ID
      - OS_NAME
    volumes:
      - ".:/app"
      - "./.docker/local/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./.docker/local/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf"
    depends_on:
      - mysql
      - redis
      - minio
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    platform: linux/amd64
    build: ".docker/local/mysql"
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ".docker/local/mysql/my.cnf:/etc/mysql/my.cnf"
      - "./storage/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  redis:
    image: redis:6.2-buster
    ports:
      - "${REDIS_PORT:-6379}:6379"

  minio:
    image: minio/minio
    ports:
      - "${MINIO_API_PORT:-9001}:9001"
      - "${MINIO_CONSOLE_PORT:-9002}:9002"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --address :9001 --console-address :9002

  create-bucket:
    image: minio/mc
    entrypoint: [ "" ]
    command:
      - /bin/sh
      - -c
      - |
        until (mc config host add minio http://minio:9001 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}) do echo 'wait until add host' && sleep 1; done;
        mc mb minio/public
        mc policy set public minio/public
        mc mb minio/private
        mc policy set private minio/private
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    depends_on:
      - minio

  mailhog:
    image: mailhog/mailhog
    ports:
      - "${MAILHOG_PORT:-8025}:8025"

  playwright:
    build:
      context: .
      dockerfile: .docker/local/playwright/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    working_dir: /app
    volumes:
      - ".:/app"
    environment:
      - PLAYWRIGHT_BASE_URL=http://nginx:80
    depends_on:
      - nginx
      - app
      - mysql
    ipc: host
    init: true
    profiles:
      - e2e
